# docker-compose's version
version: '3'
services: 
  web: 
    build: .
    volumes: 
      - .:/app/
      - node-module-cache:/app/node_modules
    ports: 
      - "4000:4000"
volumes:
  node-module-cache:


